apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-14T16:31:39Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "29155"
  uid: 491ae9f9-a558-4bdc-a792-542f98eac0a8
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.105.36.124
  clusterIPs:
  - 10.105.36.124
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32219
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
